# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTameshi():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tameshi(self):
    self.driver.get("https://rank.greeco-channel.com/diamtire/")
    self.driver.set_window_size(1920, 1055)
    self.driver.find_element(By.LINK_TEXT, "次の10件").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lblue:nth-child(2) .font16").click()
    self.driver.find_element(By.CSS_SELECTOR, ".widelink > div:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".post-template-default").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > .lgreen:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".forpc > tbody").click()
  
